---
- name: install dependency packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
- name: add apt signing key
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present
- name: add grafana repository
  apt_repository:
    filename: grafana
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present

