---
- name: Install dependency packages
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
- name: Add apt signing key
  ansible.builtin.apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present
- name: Add grafana repository
  ansible.builtin.apt_repository:
    filename: grafana
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present
