---
- name: Install dependency packages
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
- name: Create GPG key directory
  ansible.builtin.file:
    path: "{{ grafana_apt_key_dest | dirname }}"
    state: directory
    mode: "0755"
- name: Download GPG key
  ansible.builtin.get_url:
    url: "{{ grafana_apt_key_url }}"
    dest: "{{ grafana_apt_key_download_dest }}"
    mode: "0644"
  register: gpg_key_download_result
- name: Convert GPG key
  ansible.builtin.command:
    cmd: gpg --dearmor -o {{ grafana_apt_key_dest }} {{ grafana_apt_key_download_dest }}
  when: gpg_key_download_result is changed
- name: Add grafana repository
  ansible.builtin.apt_repository:
    filename: grafana
    repo: deb [signed-by={{ grafana_apt_key_dest }}] https://packages.grafana.com/oss/deb stable main
    state: present
