---
- name: grafana is active and enabled on system startup
  ansible.builtin.systemd:
    name: grafana-server
    state: started
    enabled: true
- name: allow grafana port
  community.general.ufw:
    rule: allow
    port: "{{ grafana_port | string }}"
    proto: tcp
  when: grafana_allow_connect_other_host | default(false)
