---
- name: update grafana base settings
  community.general.ini_file:
    path: "{{ grafana_config_dir }}/grafana.ini"
    section: "{{ item.section }}"
    option: "{{ item.option | default(omit) }}"
    value: "{{ item.value | default(omit) }}"
    owner: root
    group: grafana
    mode: "0640"
  loop: "{{ grafana_base_cfg }}"
  notify: restart grafana
- name: create/update grafana settings
  ansible.builtin.template:
    src: custom.yml.j2
    dest: "{{ grafana_config_provisioning_dir }}/{{ item.name }}/custom.yml"
    owner: root
    group: grafana
    mode: "0640"
  notify: restart grafana
  loop:
    - name: access-control
      value: "{{ grafana_access_control_cfg }}"
    - name: dashboards
      value: "{{ grafana_dashboards_cfg }}"
    - name: datasources
      value: "{{ grafana_datasources_cfg }}"
    - name: notifiers
      value: "{{ grafana_notifiers_cfg }}"
    - name: plugins
      value: "{{ grafana_plugins_cfg }}"
